const fs = require('fs');
let content = fs.readFileSync('resources/views/Admin/Dashboard/dashboard.blade.php', 'utf8');
content = content.replace(/alert\('Pengaturan berhasil disimpan!'\);/g, "this.addToast('Pengaturan berhasil disimpan!', 'success');");
content = content.replace(/alert\('Gagal menyimpan pengaturan: ' \+ \(data\.message \|\| 'Error tidak diketahui'\)\);/g, "this.addToast('Gagal menyimpan pengaturan: ' + (data.message || 'Error tidak diketahui'), 'error');");
content = content.replace(/alert\('Terjadi kesalahan jaringan\.'\);/g, "this.addToast('Terjadi kesalahan jaringan.', 'error');");
content = content.replace(/alert\('Nama dan Slug toko wajib diisi!'\);/g, "this.addToast('Nama dan Slug toko wajib diisi!', 'error');");
content = content.replace(/alert\('Ukuran file maksimal 2MB'\);/g, "this.addToast('Ukuran file maksimal 2MB', 'error');");
content = content.replace(/alert\('Silakan masukkan nama\/nomor meja!'\);/g, "this.addToast('Silakan masukkan nama/nomor meja!', 'error');");
content = content.replace(/alert\("Nama, Harga, dan Kategori wajib diisi!"\);/g, "this.addToast('Nama, Harga, dan Kategori wajib diisi!', 'error');");
fs.writeFileSync('resources/views/Admin/Dashboard/dashboard.blade.php', content);
